package alertdetector

import "math"

const (
	segmentMs   = 250 // Sub-segment size for envelope analysis
	refSegments = 32  // Reference window for length-independent envelope metrics
)

// Metrics holds all computed signal features for the analyzed audio
type Metrics struct {
	MaxZCR          float64 // highest zero-crossing rate among segments
	HighPitchRatio  float64 // fraction of segments with ZCR above high-pitch threshold
	OverallTonality float64 // crossing regularity of all segments (low = tonal)
	SpectralPurity  float64 // energy concentration around dominant frequency (high = pure tone)
	MidHighRatio    float64 // energy in 800-6000Hz vs total (high = alarm-like pitch range)
	BandFocus       float64 // energy concentration in one band (high = narrow-band signal)
	OscCV           float64 // coefficient of variation of RMS oscillations
	EnvRegularity   float64 // envelope rhythm regularity (low = regular like alarm)
	Oscillations    float64 // rate of significant direction changes in envelope
}

// Result is returned by Analyze when an alert is detected
type Result struct {
	Metrics Metrics // all computed signal features
}

type Detector struct {
	sampleRate          int
	samplesPerSeg       int
	iirA1, iirA2, iirA3 float64 // pre-computed IIR filter coefficients
}

// New creates a Detector for the given sample rate
func New(sampleRate int) *Detector {
	if sampleRate <= 0 {
		panic("alertdetector: sample rate must be positive")
	}

	sr := float64(sampleRate)
	return &Detector{
		sampleRate:    sampleRate,
		samplesPerSeg: sampleRate * segmentMs / 1000,
		// Single-pole IIR alpha = 1 - exp(-2*pi*fc/fs)
		iirA1: 1 - math.Exp(-2*math.Pi*400/sr),
		iirA2: 1 - math.Exp(-2*math.Pi*1500/sr),
		iirA3: 1 - math.Exp(-2*math.Pi*4000/sr),
	}
}

// Analyze runs alert detection on a PCM sample buffer
func (d *Detector) Analyze(samples []int16) *Result {
	m := d.computeMetrics(samples)
	for _, r := range alertRules {
		if r.match(m) {
			return &Result{Metrics: m}
		}
	}
	return nil
}

// computeMetrics runs the full feature-extraction pipeline and returns a Metrics struct
func (d *Detector) computeMetrics(samples []int16) Metrics {
	seg := d.computeSegments(normalizeSamples(samples, rms(samples)))
	return Metrics{
		MaxZCR:          seg.maxZCR,
		HighPitchRatio:  seg.highPitchRatio,
		OverallTonality: seg.overallTonality,
		SpectralPurity:  seg.spectralPurity,
		MidHighRatio:    seg.midHighRatio,
		BandFocus:       seg.bandFocus,
		OscCV:           chunkedCV(seg.segRMS),
		EnvRegularity:   chunkedEnvReg(seg.segRMS),
		Oscillations:    max(countSwings(seg.segRMS), countSwings(seg.segZCR)),
	}
}

// rule defines min/max bounds for each metric (0 = don't check)
// A rule matches when all non-zero bounds are satisfied
type rule struct {
	minMaxZCR, maxMaxZCR         float64
	minHPR, maxHPR               float64
	minOverallTon, maxOverallTon float64
	minPurity, maxPurity         float64
	minMidHigh, maxMidHigh       float64
	minBandFocus, maxBandFocus   float64
	minOscCV, maxOscCV           float64
	minEnvReg, maxEnvReg         float64
	minOsc, maxOsc               float64
}

func (r rule) match(m Metrics) bool {
	return (r.minMaxZCR == 0 || m.MaxZCR >= r.minMaxZCR) &&
		(r.maxMaxZCR == 0 || m.MaxZCR < r.maxMaxZCR) &&
		(r.minHPR == 0 || m.HighPitchRatio >= r.minHPR) &&
		(r.maxHPR == 0 || m.HighPitchRatio < r.maxHPR) &&
		(r.minOverallTon == 0 || m.OverallTonality > r.minOverallTon) &&
		(r.maxOverallTon == 0 || m.OverallTonality < r.maxOverallTon) &&
		(r.minPurity == 0 || m.SpectralPurity > r.minPurity) &&
		(r.maxPurity == 0 || m.SpectralPurity < r.maxPurity) &&
		(r.minMidHigh == 0 || m.MidHighRatio > r.minMidHigh) &&
		(r.maxMidHigh == 0 || m.MidHighRatio < r.maxMidHigh) &&
		(r.minBandFocus == 0 || m.BandFocus > r.minBandFocus) &&
		(r.maxBandFocus == 0 || m.BandFocus < r.maxBandFocus) &&
		(r.minOscCV == 0 || m.OscCV > r.minOscCV) &&
		(r.maxOscCV == 0 || m.OscCV < r.maxOscCV) &&
		(r.minEnvReg == 0 || m.EnvRegularity > r.minEnvReg) &&
		(r.maxEnvReg == 0 || m.EnvRegularity < r.maxEnvReg) &&
		(r.minOsc == 0 || m.Oscillations >= r.minOsc) &&
		(r.maxOsc == 0 || m.Oscillations < r.maxOsc)
}

// RULES AUTO-GENERATED BY OPTIMIZE_TEST.GO ------------------------------------------
var alertRules = []rule{
	{maxOscCV: 0.257, maxOverallTon: 0.92, minPurity: 0.723, minMidHigh: 0.345},
	{minMidHigh: 0.594, minBandFocus: 0.451, minMaxZCR: 0.051, maxHPR: 0.171, maxOsc: 0.209, maxEnvReg: 0.879},
	{maxBandFocus: 0.441, maxOscCV: 0.35, minPurity: 0.527, minMaxZCR: 0.081, maxOverallTon: 0.913},
	{minHPR: 0.797, maxOscCV: 0.49, maxOsc: 0.287, maxMidHigh: 0.631, minEnvReg: 0.246},
	{maxBandFocus: 0.496, minOsc: 0.285, minPurity: 0.651, maxMidHigh: 0.618, maxOsc: 0.446, maxOverallTon: 1.598},
	{maxBandFocus: 0.575, maxMidHigh: 0.4, minPurity: 0.617, maxOverallTon: 1.358},
	{maxOscCV: 0.167, minOverallTon: 1.392, minMidHigh: 0.083, maxMidHigh: 0.132, minOscCV: 0.118, maxEnvReg: 0.549},
	{maxBandFocus: 0.448, minBandFocus: 0.408, minOscCV: 0.498, maxOscCV: 0.597, maxHPR: 0.303},
	{minMidHigh: 0.533, minOsc: 0.257, maxPurity: 0.522, maxHPR: 0.009},
	{minHPR: 0.478, minPurity: 0.738, minOscCV: 0.696, minOsc: 0.329, maxMaxZCR: 0.181},
	{maxOsc: 0.094, minEnvReg: 0.466, minBandFocus: 0.492, minMidHigh: 0.345, minMaxZCR: 0.029},
	{maxOsc: 0.121, maxBandFocus: 0.448, minPurity: 0.683, maxOscCV: 0.484},
	{maxOscCV: 0.406, minOscCV: 0.28, maxMidHigh: 0.385, minMidHigh: 0.309},
}
